Update dot_config/git/exact_hooks/executable_post-checkout Update dot_config/git/exact_hooks/executable_post-commit Update dot_config/git/exact_hooks/executable_post-merge Remove dot_config/git/exact_hooks/executable_post-rewrite Update dot_config/git/exact_hooks/executable_pre-push

diff --git a/dot_config/git/exact_hooks/executable_post-checkout b/dot_config/git/exact_hooks/executable_post-checkout
--- a/dot_config/git/exact_hooks/executable_post-checkout
+++ b/dot_config/git/exact_hooks/executable_post-checkout
@@ -1,5 +1,9 @@
 #!/bin/sh
 
-set -e
+command -v git-lfs >/dev/null 2>&1 || {
+  echo "\nThis repository is configured for Git LFS but 'git-lfs' was not found on your path." \
+    "If you no longer wish to use Git LFS, remove this hook by deleting .git/hooks/pre-push.\n" >&2
+  exit 2
+}
 
-git lfs post-checkout "$@"
+exec git lfs post-checkout "$@"
